Update mkshrc
line functions

diff --git a/mkshrc b/mkshrc
--- a/mkshrc
+++ b/mkshrc
@@ -84,65 +84,43 @@ git config --global --add push.autoSetupRemote true
 }
 
 replaceline() {
-    # Check if the required arguments are provided
-    if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ]; then
-        echo "Usage: replaceline <line_number> <substitution> <file_path>"
-        return 1
-    fi
+    local line_number=$1
+    local replacement=$2
+    local filename=$3
 
-    line_number="$1"
-    substitution="$2"
-    file_path="$3"
-
-    # Perform the line replacement using sed
-    sed -i "$line_number s/.*/$substitution/" "$file_path"
+    # Use sed to replace the specified line in the file
+    sed -i "${line_number}s/.*/$replacement/" "$filename"
 }
 
 printline() {
-    line_number="$1"
-    file_path="$2"
+    local file_path=$1
+    local start_line=$2
+    local end_line=$3
 
-    if [ -z "$line_number" ] || [ -z "$file_path" ]; then
-        echo "Usage: printline <line number or range> <file path>"
+    if [ -z "$file_path" ]; then
+        echo "File path is required."
         return 1
     fi
 
-    line_range=(${(s:-:)line_number})
-    start_line=$((line_range[1] + 1))
-    end_line=$((line_range[2] + 1))
-
-    if [ -n "${line_range[2]}" ]; then
-        sed_range="$start_line,${end_line}p"
-    else
-        sed_range="${start_line}p"
-    fi
-
-    if [ -f "$file_path" ]; then
-        sed -n "$sed_range" "$file_path"
-    else
-        echo "Error: File '$file_path' not found."
+    if [ -z "$start_line" ] || [ -z "$end_line" ]; then
+        echo "Start and end lines are required."
         return 1
     fi
+
+    # Use bat to colorize and paginate the output
+    bat --style=plain --pager=never --line-range="$start_line:$end_line" --color=always "$file_path" | rg --color=always .
+
+    return $?
 }
 
 replaceall() {
-    file_path="$1"
-    search_string="$2"
-    replacement="$3"
-    num_replacements="$4"
-
-    if [ "$num_replacements" -eq 0 ]; then
-        num_replacements="g"
-    fi
-
-    line_numbers=$(sed -n "/$search_string/=" "$file_path")
-    sed -i "s/$search_string/$replacement/$num_replacements" "$file_path"
-
-    for line_number in $line_numbers; do
-        echo "Replacement occurred on line $line_number"
-    done
+    local search_string=$1
+    local replace_string=$2
+    local n=$3
+    local file_path=$4
+    cp "$file_path" "$file_path.bak"
+    sed -i "s/$search_string/$replace_string/$n" "$file_path"
 }
-
 
 function instsearch {
   if test $# -eq 0; then
